Repository OneInA1E6/Capstone, pull requests merged in 2022-11, with the labels that each got.

#88 Add the formatted meeting to the repo
  Documents/Meetings/Client Meetings/client_meeting_10-31-2022.md
Labels: Chore

#89 Create team_meeting_11-01-2022.md
  Documents/Meetings/Team Meetings/team_meeting_11-01-2022.md
Labels: Chore

#94 4 accommodations new acc page
  src/app/Http/Controllers/AccommodationController.php
  src/app/Models/Accommodation.php
  src/database/seeders/UserSeeder.php
  src/resources/js/Pages/Accommodations.vue
  src/resources/js/Pages/Accommodations/Index.vue
  src/routes/web.php
Labels: Task

#96 fixed issue with data showing
  src/resources/js/Pages/Booking/Index.vue
Labels: Task

#97 85 dashboard controller
  src/app/Http/Controllers/AccommodationController.php
  src/app/Http/Controllers/DashboardController.php
  src/resources/js/Composables/DashboardGet.js
  src/resources/js/Pages/Accommodations/Index.vue
  src/resources/js/Pages/Dashboard/Index.vue
  src/routes/web.php
Labels: Task

#100 Add client meeting 8 to repo
  Documents/Meetings/Client Meetings/client_meeting_11-07-2022.md
Labels: Chore

#103 Add the small client meeting
  Documents/Meetings/Client Meetings/client_meeting_11-14-2022.md
Labels: Chore

#105 104 team meeting 2011 11 15
  Documents/Meetings/Team Meetings/team_meeting_11-15-202.md
Labels: Chore

#106 66 make a general admin layout
  src/resources/js/Components/Sidebar/SideBar.vue
  src/resources/js/Layouts/AppLayout.vue
  src/resources/js/Pages/Accommodations/Index.vue
  src/resources/js/Pages/Booking/Index.vue
  src/resources/js/Pages/Dashboard.vue
  src/resources/js/Pages/Dashboard/Index.vue
  src/resources/js/Pages/Group/Index.vue
Labels: Task

#107 101 data bookings
  src/app/Http/Controllers/BookingController.php
  src/resources/js/Pages/Booking/Index.vue
  src/routes/web.php
Labels: Task

#110 108 landing page
  src/resources/images/GH-logo.jpg
  src/resources/images/fire-burning-down-a-building.jpg
  src/resources/js/Components/Sidebar/SideBar.vue
  src/resources/js/Pages/Welcome.vue
  src/resources/js/Pages/index.vue
  src/routes/web.php
Labels: Task

#112 delet button
  src/resources/js/Pages/index.vue
Labels: Chore

#118 117 glohaven photo
  src/resources/images/GEMSLogo.svg
  src/resources/images/GH-logo.jpg
  src/resources/js/Components/Sidebar/SideBar.vue
  src/resources/js/Pages/Booking/Index.vue
  src/resources/js/Pages/index.vue
Labels: Chore

#122 119 reformat bookings page to display bookings
  src/app/Http/Controllers/BookingController.php
  src/resources/js/Pages/Booking/CreateEdit.vue
  src/resources/js/Pages/Booking/Index.vue
  src/routes/web.php
Labels: Task

#125 121 figure out the hierarchy of our models
  src/app/Models/Accommodation.php
  src/app/Models/Booking.php
  src/app/Models/Group.php
  src/app/Models/GroupDetails.php
  src/app/Models/Region.php
  src/database/seeders/AccommodationSeeder.php
  src/database/seeders/DatabaseSeeder.php
  src/database/seeders/RegionSeeder.php
Labels: Task

#127 Change all of the show functions to index
  src/app/Http/Controllers/AccommodationController.php
  src/app/Http/Controllers/BookingController.php
  src/app/Http/Controllers/DashboardController.php
  src/app/Http/Controllers/GroupController.php
  src/routes/web.php
Labels: Chore

#129 119 Fixed booking page to now allow deletion as well as some flash messages for the user
  package-lock.json
  src/app/Http/Controllers/BookingController.php
  src/app/Http/Middleware/HandleInertiaRequests.php
  src/package-lock.json
  src/package.json
  src/resources/MdiIcons/midIcons.svg
  src/resources/js/Pages/Booking/Index.vue
  src/routes/web.php
Labels: Task, Exploration

#132 6 accommodations view acc page
  src/app/Http/Controllers/AccommodationController.php
  src/resources/js/Components/Dashboard/Table.vue
  src/resources/js/Pages/Accommodations/ShowAccommodation.vue
  src/routes/web.php
Labels: Task

#134 131 edit bookings
  src/app/Http/Controllers/BookingController.php
  src/resources/js/Pages/Booking/CreateEdit.vue
  src/resources/js/Pages/Booking/Index.vue
  src/routes/web.php
Labels: Task

#137 Changed styling on login and register page
  src/resources/js/Components/ApplicationLogo.vue
  src/resources/js/Components/Sidebar/SideBar.vue
  src/resources/js/Layouts/GuestLayout.vue
  src/resources/js/Pages/Accommodations/Index.vue
  src/resources/js/Pages/index.vue
Labels: Chore

#138 added link to logo
  src/resources/js/Components/ApplicationLogo.vue
  src/resources/js/Components/Sidebar/SideBar.vue
Labels: Chore

#140 70 add controller functionality for the groups page
  src/app/Http/Controllers/GroupController.php
  src/app/Models/Group.php
  src/app/Models/GroupDetails.php
  src/database/migrations/2022_11_04_142156_create_group_details_table.php
  src/package-lock.json
  src/package.json
  src/resources/js/Components/Card.vue
  src/resources/js/Components/NavLink.vue
  src/resources/js/Components/Sidebar/SideBar.vue
  src/resources/js/Pages/Accommodations/Index.vue
  src/resources/js/Pages/Booking/Index.vue
  src/resources/js/Pages/Group/CreateEdit.vue
  src/resources/js/Pages/Group/Index.vue
  src/resources/js/Pages/Group/ShowGroup.vue
  src/resources/js/Pages/index.vue
  src/resources/js/app.js
  src/resources/mdiIcons/mdiIcons.svg
  src/routes/web.php
Labels: Task

#141 135 delete accommodation with no bookings
  src/app/Http/Controllers/AccommodationController.php
  src/database/factories/AccommodationFactory.php
  src/database/seeders/AccommodationSeeder.php
  src/database/seeders/GroupSeeder.php
  src/resources/js/Pages/Accommodations/Index.vue
Labels: Task

#143 142 resize logo
  src/resources/js/Components/ApplicationLogo.vue
  src/resources/js/Components/Sidebar/SideBar.vue
  src/resources/js/Pages/Accommodations/Index.vue
Labels: Chore
